=== BackupTheBerlios/alricg-svn/alricg/ressourcen/daten/schema/library-schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 * Created on 23.01.2005
 *
 * This file is part of the project ALRICG. The file is copyright
 * protected and under the GNU General Public License.
 * For more information see "http://alricg.die3sphaere.de/".
 *
-->
<xsd:schema targetNamespace="http://alricg.die3sphaere.de/lib/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://alricg.die3sphaere.de/lib/">
	<xsd:element name="alricgXML">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="preamble">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="version" type="xsd:string" use="required"/>
								<xsd:attribute name="author" type="xsd:string" use="optional"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="library">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="short" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="middle" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="long" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="errorMsg" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="toolTip" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="entry">
		<xsd:sequence>
			<xsd:element name="e" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="lang" type="xsd:string" use="required"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== BackupTheBerlios/alricg-svn/alricg/ressourcen/daten/text/library.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- This file is part of the project ALRICG. -->
<n:alricgXML xmlns:n="http://alricg.die3sphaere.de/lib/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alricg.die3sphaere.de/lib/
..\schema\library-schema.xsd">
  <preamble version="v0.1" author="V.Strelow">
    The german standard text-library for Alricg-Project. 
    You can change the text, but DON'T CHANGE THE KEY-WORD!!
    The text is identified by the key-word.
    
    library-element has 5 under-elements:
      short - Text has only one word.
      middle - Text has two or three words.
      long - Text has more as three words.
      errorMsg - Error Messeges
      toolTip - Text for ToolTip messages
  </preamble>
  <library>
    <short> 
<!-- *********** Namen und Abkürzungen für Charakterwerte *********** -->
      <entry key="MU">
        <e lang="DE">MU</e>
        <e lang="EN">COU</e>
      </entry>
      <entry key="KL">
        <e lang="DE">KL</e>
        <e lang="EN">CL</e>
      </entry>
      <entry key="IN">
        <e lang="DE">IN</e>
        <e lang="EN">INT</e>
      </entry>
      <entry key="CH">
        <e lang="DE">CH</e>
        <e lang="EN">CHA</e>
      </entry>
      <entry key="FF">
        <e lang="DE">FF</e>
        <e lang="EN">DEX</e>
      </entry>
      <entry key="GE">
        <e lang="DE">GE</e>
        <e lang="EN">AG</e>
      </entry>
      <entry key="KO">
        <e lang="DE">KO</e>
        <e lang="EN">CON</e>
      </entry>
      <entry key="KK">
        <e lang="DE">KK</e>
        <e lang="EN">STR</e>
      </entry>
      <entry key="GS">
        <e lang="DE">GS</e>
        <e lang="EN">SPD</e>
      </entry>
      <entry key="INI">
        <e lang="DE">INI</e>
        <e lang="EN">INIT</e>
      </entry>
      <entry key="MR">
        <e lang="DE">MR</e>
        <e lang="EN">MR</e>
      </entry>
      <entry key="LeP">
        <e lang="DE">LeP</e>
        <e lang="EN">AdP</e>
      </entry>
      <entry key="AsP">
        <e lang="DE">AsP</e>
        <e lang="EN">AsE</e>
      </entry>
      <entry key="AuP">
        <e lang="DE">AuP</e>
        <e lang="EN">END</e>
      </entry>      
      <entry key="KA">
        <e lang="DE">KA</e>
        <e lang="EN">APCred</e>
      </entry>
      <entry key="SO">
        <e lang="DE">SO</e>
        <e lang="EN">SS</e>
      </entry>      
      <entry key="AT">
        <e lang="DE">AT</e>
        <e lang="EN">BAV</e>
      </entry>
      <entry key="PA">
        <e lang="DE">PA</e>
        <e lang="EN">BPV</e>
      </entry>    
      <entry key="FK">
        <e lang="DE">FK</e>
        <e lang="EN">RBV</e>
      </entry>  
      
      <entry key="Mut">
        <e lang="DE">Mut</e>
        <e lang="EN">Courage</e>
      </entry>
      <entry key="Klugheit">
        <e lang="DE">Klugheit</e>
        <e lang="EN">Cleverness</e>        
      </entry>
      <entry key="Intuition">
        <e lang="DE">Intuition</e>
        <e lang="EN">Intuition</e>
      </entry>
      <entry key="Charisma">
        <e lang="DE">Charisma</e>
        <e lang="EN">Charisma</e>        
      </entry>
      <entry key="Fingerfertigkeit">
        <e lang="DE">Fingerfertigkeit</e>
        <e lang="EN">Dexterity</e>
      </entry>
      <entry key="Gewandheit">
        <e lang="DE">Gewandheit</e>
        <e lang="EN">Agility</e>
      </entry>
      <entry key="Konstitution">
        <e lang="DE">Konstitution</e>
        <e lang="EN">Constitution</e>
      </entry>
      <entry key="Koerperkraft">
        <e lang="DE">Körperkraft</e>
        <e lang="EN">Strength</e>      
      </entry>
      <entry key="Geschwindigkeit">
        <e lang="DE">Geschwindigkeit</e>
        <e lang="EN">Speed</e>
      </entry>
      <entry key="Initiative">
        <e lang="DE">Initiative</e>
        <e lang="EN">Initiative</e>
      </entry>
      <entry key="Magieresistenz">
        <e lang="DE">Magieresistenz</e>
        <e lang="EN">Resistance to Magic</e>
      </entry>
      <entry key="Lebenspunkte">
        <e lang="DE">Lebenspunkte</e>
        <e lang="EN">Adventure Points</e>
      </entry>
      <entry key="Astralpunkte">
        <e lang="DE">Astralpunkte</e>
        <e lang="EN">Astral Energy</e>
      </entry>
      <entry key="Ausdauerpunkt">
        <e lang="DE">Ausdauerpunkt</e>
        <e lang="EN">Endurance</e>
      </entry>      
      <entry key="Karmaernergie">
        <e lang="DE">Karmaernergie</e>
        <e lang="EN">AP Credit</e>
      </entry>
      <entry key="Sozialstatus">
        <e lang="DE">Sozialstatus</e>
        <e lang="EN">Social Standing</e>
      </entry>      
      <entry key="AttackeBasis">
        <e lang="DE">Attacke-Basis</e>
        <e lang="EN">Base Attack Value</e>
      </entry>
      <entry key="ParadeBasis">
        <e lang="DE">Parade-Basis</e>
        <e lang="EN">Base Parry Value</e>
      </entry>
      <entry key="FernkampfBasis">
        <e lang="DE">Fernkampf-Basis</e>
        <e lang="EN">Base Ranged Value</e>
      </entry>

<!-- *************** Werte für CharKomponenten ********************************** --> 		
      <entry key="RAS">
        <e lang="DE">Rasse</e>
	  </entry>
      <entry key="KUL">
        <e lang="DE">Kultur</e>
      </entry>
      <entry key="PRO">
        <e lang="DE">Profession</e>
      </entry>
	  <entry key="RAV">
        <e lang="DE">Rassen Variante</e>
      </entry>
      <entry key="KUV">
        <e lang="DE">Kultur Variante</e>
	  </entry>
      <entry key="PRV">
        <e lang="DE">Profession Variante</e>
      </entry>	
      <entry key="ZPR">
        <e lang="DE">Zusatzprofession</e>
      </entry>
	  <entry key="VOR">
        <e lang="DE">Vorteil</e>
      </entry>
      <entry key="GAB">
        <e lang="DE">Gabe</e>
	  </entry>
      <entry key="NAC">
        <e lang="DE">Nachteil</e>
      </entry>
      <entry key="SF">
        <e lang="DE">Sonderfertigkeit</e>
      </entry>
	  <entry key="LRK">
        <e lang="DE">RitualKenntnise</e>
      </entry>
      <entry key="TAL">
        <e lang="DE">Talent</e>
      </entry>
	  <entry key="SPR">
        <e lang="DE">Sprache</e>
      </entry>
      <entry key="SFT">
        <e lang="DE">Schrift</e>
	  </entry>
      <entry key="ZAU">
        <e lang="DE">Zauber</e>
      </entry>
      <entry key="LIT">
        <e lang="DE">Liturgie</e>
      </entry>
	  <entry key="RIT">
        <e lang="DE">Ritual</e>
      </entry>				
      <entry key="AUS">
        <e lang="DE">Ausrüstung</e>
      </entry>
      <entry key="FAH">
        <e lang="DE">Fahrzeug</e>
      </entry>
	  <entry key="NKW">
        <e lang="DE">Nahkampfwaffe</e>
      </entry>
      <entry key="FKW">
        <e lang="DE">Fernkampfwaffe</e>
      </entry>
      <entry key="RUE">
        <e lang="DE">Rüstung</e>
      </entry>
	  <entry key="SLD">
        <e lang="DE">Schild</e>
      </entry>
      <entry key="DAE">
        <e lang="DE">Dämonenpakt</e>
      </entry>
      <entry key="SGA">
        <e lang="DE">Schwarze Gabe</e>
      </entry>
	  <entry key="TIE">
        <e lang="DE">Tier</e>
      </entry>
	  <entry key="REG">
        <e lang="DE">Region</e>
      </entry>
      <entry key="GOT">
        <e lang="DE">Gottheit</e>
      </entry>
      <entry key="REP">
        <e lang="DE">Repräsentation</e>
      </entry>
	  <entry key="EIG">
        <e lang="DE">Eigenschaft</e>
      </entry>
	  <entry key="SR">
        <e lang="DE">Sonderregel</e>
      </entry>
		
<!-- *************** Werte für Talent Enums **********************************  -->
      <entry key="kampf">
        <e lang="DE">Kampf</e>
        <e lang="EN">Combat Abilities</e>
      </entry>
      <entry key="koerper">
        <e lang="DE">Körper</e>
        <e lang="EN">Physical Abilities</e>
      </entry>
      <entry key="gesellschaft">
        <e lang="DE">Gesellschaft</e>
        <e lang="EN">Social Abilities</e>
      </entry>
      <entry key="natur">
        <e lang="DE">Natur</e>
        <e lang="EN">Nature Abilitiles</e>
      </entry>
      <entry key="wissen">
        <e lang="DE">Wissen</e>
        <e lang="EN">Lore Abilities</e>
      </entry>
      <entry key="handwerk">
        <e lang="DE">Handwerk</e>
        <e lang="EN">Artisan Abilities</e>
      </entry>
      <entry key="basis">
        <e lang="DE">Basis</e>
        <e lang="EN">Base</e>
      </entry>
      <entry key="spezial">
        <e lang="DE">Spezial</e>
        <e lang="EN">Special</e>
      </entry>
      <entry key="beruf">
        <e lang="DE">Beruf</e>
        <e lang="EN">Professional</e>
      </entry>

<!-- *************** Enums für Zaubermerkmale*********************************  --> 
      <entry key="antimagie">
        <e lang="DE">Antimagie</e>
        <e lang="EN">Resistance to Magic</e>
      </entry>
      <entry key="beschwoerung">
        <e lang="DE">Beschwörung</e>
        <e lang="EN">Conjuration</e>
      </entry>
      <entry key="daemonisch">
        <e lang="DE">Dämonisch</e>
        <e lang="EN">Demonic</e>
      </entry>
      <entry key="eigenschaften">
        <e lang="DE">Eigenschaften</e>
        <e lang="EN">Properties</e>
      </entry>
      <entry key="einfluss">
        <e lang="DE">Einfluss</e>
        <e lang="EN">Influence</e>
      </entry>
      <entry key="elementar">
        <e lang="DE">Elementar</e>
        <e lang="EN">Elementray</e>
      </entry>
      <entry key="elementar (feuer)">
        <e lang="DE">Elementar (Feuer)</e>
        <e lang="EN">Elementaty (Fire)</e>
      </entry>
      <entry key="elementar (wasser)">
        <e lang="DE">Elementar (Wasser)</e>
